# Generated by Django 4.2.14 on 2024-08-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='est_reg',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
