# Generated by Django 4.2.14 on 2024-08-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersAuth', '0002_remove_user_is_active_user_est_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=125, unique=True),
        ),
    ]
